/*
 * Bled (Base Library for Easy Decompression) - Size related dependencies
 *
 * Mostly generated by AI - No copyright assigned.
 *
 * Licensed under GPLv2 or later, see file LICENSE in this source tree.
 */

#ifdef _CRTDBG_MAP_ALLOC
#include <stdlib.h>
#include <crtdbg.h>
#endif

#include "libbb.h"
#include "bb_archive.h"
#include "bled.h"

/* -------------------------------------------------------------------------
 * Internal helpers
 * ---------------------------------------------------------------------- */

#define DECOMP_SIZE_ERROR    ((int64_t)-1)
#define DECOMP_SIZE_UNKNOWN  ((int64_t)-2)
#define DECOMP_IO_ERROR      ((int64_t)-3)

 /** Read exactly n bytes from fd into buf; returns 0 on success, -1 on error. */
static int read_exact(int fd, void* buf, size_t n)
{
	uint8_t* p = (uint8_t*)buf;
	while (n > 0) {
		int got = _read(fd, p, (unsigned)n);
		if (got <= 0)
			return -1;
		p += got;
		n -= (size_t)got;
	}
	return 0;
}

int64_t get_uncompress_size_none(int fd)
{
	return DECOMP_SIZE_UNKNOWN;
}

/* -------------------------------------------------------------------------
 * PKZIP
 *
 * Local File Header layout (all fields little-endian):
 *
 *   Offset  Size  Field
 *      0      4   Signature (0x04034b50)
 *      4      2   Version needed
 *      6      2   General purpose bit flag
 *      8      2   Compression method
 *     10      2   Last mod file time
 *     12      2   Last mod file date
 *     14      4   CRC-32
 *     18      4   Compressed size   (0xFFFFFFFF → see ZIP64 Extra Field)
 *     22      4   Uncompressed size (0xFFFFFFFF → see ZIP64 Extra Field)
 *     26      2   File name length
 *     28      2   Extra field length
 *     30      ?   File name
 *     30+n    ?   Extra field
 *
 * ZIP64 Extra Field tag: 0x0001
 * Within the ZIP64 extra field block the fields appear only when the
 * corresponding 32-bit field in the Local Header is 0xFFFFFFFF:
 *   - Original size  (8 bytes LE)  ← first, if uncompressed == 0xFFFFFFFF
 *   - Compressed size (8 bytes LE) ← second, if compressed == 0xFFFFFFFF
 * ---------------------------------------------------------------------- */

#define ZIP_LFH_SIG        UINT32_C(0x04034b50)
#define ZIP_LFH_HDR_SIZE   30
#define ZIP64_EXTRA_TAG    0x0001
#define ZIP32_NEEDS_ZIP64  UINT32_C(0xFFFFFFFF)

static int64_t get_uncompress_size_zip(int fd)
{
	uint8_t hdr[ZIP_LFH_HDR_SIZE];

	if (lseek(fd, 0, SEEK_SET) < 0)
		return DECOMP_SIZE_ERROR;
	if (read_exact(fd, hdr, ZIP_LFH_HDR_SIZE))
		return DECOMP_SIZE_ERROR;

	/* Verify Local File Header signature. */
	if (get_le32(hdr + 0) != ZIP_LFH_SIG)
		return DECOMP_SIZE_ERROR;

	uint32_t uncomp32 = get_le32(hdr + 22);
	uint32_t comp32 = get_le32(hdr + 18);
	uint16_t fname_len = get_le16(hdr + 26);
	uint16_t extra_len = get_le16(hdr + 28);

	/* Fast path: 32-bit field is valid. */
	if (uncomp32 != ZIP32_NEEDS_ZIP64)
		return (int64_t)uncomp32;

	/* Need ZIP64 Extra Field – skip over the file name first. */
	if (lseek(fd, (int64_t)fname_len, SEEK_CUR) < 0)
		return DECOMP_SIZE_ERROR;

	/* Walk the extra field TLV blocks looking for tag 0x0001. */
	uint16_t remaining = extra_len;
	while (remaining >= 4) {
		uint8_t tag_buf[4];
		if (read_exact(fd, tag_buf, 4))
			return DECOMP_SIZE_ERROR;
		remaining = (uint16_t)(remaining - 4);

		uint16_t tag = get_le16(tag_buf + 0);
		uint16_t dlen = get_le16(tag_buf + 2);

		if (tag == ZIP64_EXTRA_TAG) {
			/*
			 * Fields are present only when the corresponding 32-bit value is
			 * 0xFFFFFFFF.  Uncompressed size comes first; we need 8 bytes.
			 */
			if (uncomp32 == ZIP32_NEEDS_ZIP64) {
				if (dlen < 8 || remaining < 8)
					return DECOMP_SIZE_ERROR;
				uint8_t sz[8];
				if (read_exact(fd, sz, 8))
					return DECOMP_SIZE_ERROR;
				return (int64_t)get_le64(sz);
			}
		}

		/* Skip this block. */
		if (dlen > remaining) return DECOMP_SIZE_ERROR;
		if (lseek(fd, (int64_t)dlen, SEEK_CUR) < 0)
			return DECOMP_SIZE_ERROR;
		remaining = (uint16_t)(remaining - dlen);
		(void)comp32; /* suppress unused-variable warning */
	}

	return DECOMP_SIZE_ERROR; /* ZIP64 tag not found */
}

/* -------------------------------------------------------------------------
 * GZIP
 *
 * The ISIZE field is the last 4 bytes of the file (little-endian uint32).
 * It holds the decompressed size modulo 2^32.
 *
 * Header magic: 0x1F 0x8B
 * ---------------------------------------------------------------------- */

#define GZIP_MAGIC_0 0x1F
#define GZIP_MAGIC_1 0x8B

static int64_t get_uncompress_size_gz(int fd)
{
	/* Verify magic bytes at offset 0. */
	uint8_t magic[2];
	if (lseek(fd, 0, SEEK_SET) < 0)
		return DECOMP_SIZE_ERROR;
	if (read_exact(fd, magic, 2))
		return DECOMP_SIZE_ERROR;
	if (magic[0] != GZIP_MAGIC_0 || magic[1] != GZIP_MAGIC_1)
		return DECOMP_SIZE_ERROR;

	/* Seek to ISIZE: last 4 bytes of the file. */
	if (lseek(fd, -4, SEEK_END) < 0)
		return DECOMP_SIZE_ERROR;

	uint8_t isize[4];
	if (read_exact(fd, isize, 4))
		return DECOMP_SIZE_ERROR;

	/*
	 * ISIZE is uint32 mod 2^32.  We return it as int64_t; callers that need
	 * to handle files >= 4 GiB must apply their own correction.
	 */
	return (int64_t)(uint64_t)get_le32(isize);
}

/* -------------------------------------------------------------------------
 * LZMA (.lzma "alone" format)
 *
 * Header layout:
 *   Offset  Size  Field
 *      0      1   Properties byte  (lc, lp, pb encoded)
 *      1      4   Dictionary size  (uint32 LE)
 *      5      8   Uncompressed size (uint64 LE;
 *                   0xFFFFFFFFFFFFFFFF → unknown, uses EOS marker)
 * ---------------------------------------------------------------------- */

#define LZMA_HEADER_SIZE    13   /* 1 + 4 + 8 */
#define LZMA_SIZE_UNKNOWN   UINT64_C(0xFFFFFFFFFFFFFFFF)

static int64_t get_uncompress_size_lzma(int fd)
{
	uint8_t hdr[LZMA_HEADER_SIZE];

	if (lseek(fd, 0, SEEK_SET) < 0)
		return DECOMP_SIZE_ERROR;
	if (read_exact(fd, hdr, LZMA_HEADER_SIZE))
		return DECOMP_SIZE_ERROR;

	/*
	 * Basic sanity check on the properties byte:
	 *   lc = props % 9,  lp = (props / 9) % 5,  pb = props / 45
	 * pb must be <= 4, so the byte must be < 225  (9 * 5 * 5).
	 */
	if (hdr[0] >= 225)
		return DECOMP_SIZE_ERROR;

	uint64_t size = get_le64(hdr + 5);
	if (size == LZMA_SIZE_UNKNOWN)
		return DECOMP_SIZE_UNKNOWN;

	return (int64_t)size;
}

/* -------------------------------------------------------------------------
 * XZ (.xz)
 *
 * An XZ file is one or more Streams, each structured as:
 *
 *   Stream Header  (12 bytes)
 *   Block(s)       (variable)
 *   Index          (variable)
 *   Stream Footer  (12 bytes)
 *
 * Stream Footer layout (little-endian unless noted):
 *   Offset  Size  Field
 *      0      4   CRC32 of bytes 4..7
 *      4      4   Backward Size  (uint32 LE; index_size = (value+1)*4)
 *      8      2   Stream Flags   (must match Stream Header flags)
 *     10      2   Magic  (0x59 0x5A)
 *
 * Index layout (immediately before Stream Footer):
 *   [0]     1    Indicator byte (must be 0x00)
 *   [1]    VLI   Number of Records
 *   per record:
 *     VLI   Unpadded Size of the compressed Block
 *     VLI   Uncompressed Size of the Block   ← what we want
 *   padding to 4-byte boundary
 *   4        CRC32 of the Index
 *
 * VLI encoding: up to 9 bytes; each byte contributes 7 bits (little-endian
 * bit order); the MSB is a continuation flag (1 = more bytes follow).
 * Maximum value: 2^63 - 1  (high bit of the 9th byte must be 0).
 * ---------------------------------------------------------------------- */

#define XZ_STREAM_FOOTER_SIZE  12
#define XZ_MAGIC_0             0xFDu
#define XZ_MAGIC_1             0x37u
#define XZ_MAGIC_2             0x7Au
#define XZ_MAGIC_3             0x58u
#define XZ_MAGIC_4             0x5Au
#define XZ_MAGIC_5             0x00u
#define XZ_FOOTER_MAGIC_0      0x59u
#define XZ_FOOTER_MAGIC_1      0x5Au

 /**
  * Decode one XZ/LZMA2 VLI from buf[*pos], advancing *pos.
  * Returns the value, or UINT64_MAX on error (overlong / overflow).
  */
static uint64_t xz_read_vli(const uint8_t* buf, size_t buf_len, size_t* pos)
{
	uint64_t val = 0;
	int      shift = 0;

	for (;;) {
		if (*pos >= buf_len)          return UINT64_MAX; /* truncated */
		if (shift >= 63)              return UINT64_MAX; /* overlong  */

		uint8_t b = buf[(*pos)++];
		val |= (uint64_t)(b & 0x7Fu) << shift;
		shift += 7;

		if (!(b & 0x80u))
			return val;
	}
}

static int64_t get_uncompress_size_xz(int fd)
{
	/* ---- Verify Stream Header magic (6 bytes at offset 0) ---- */
	uint8_t hdr_magic[6];
	if (lseek(fd, 0, SEEK_SET) < 0)
		return DECOMP_SIZE_ERROR;
	if (read_exact(fd, hdr_magic, 6))
		return DECOMP_SIZE_ERROR;
	if (hdr_magic[0] != XZ_MAGIC_0 || hdr_magic[1] != XZ_MAGIC_1 ||
		hdr_magic[2] != XZ_MAGIC_2 || hdr_magic[3] != XZ_MAGIC_3 ||
		hdr_magic[4] != XZ_MAGIC_4 || hdr_magic[5] != XZ_MAGIC_5)
		return DECOMP_SIZE_ERROR;

	/* ---- Read Stream Footer ---- */
	if (lseek(fd, -(int64_t)XZ_STREAM_FOOTER_SIZE, SEEK_END) < 0)
		return DECOMP_SIZE_ERROR;

	uint8_t footer[XZ_STREAM_FOOTER_SIZE];
	if (read_exact(fd, footer, XZ_STREAM_FOOTER_SIZE))
		return DECOMP_SIZE_ERROR;

	/* Check footer magic bytes at offset 10-11 */
	if (footer[10] != XZ_FOOTER_MAGIC_0 || footer[11] != XZ_FOOTER_MAGIC_1)
		return DECOMP_SIZE_ERROR;

	/* Backward Size: real Index size = (backward_size + 1) * 4 */
	uint32_t backward_size = get_le32(footer + 4);
	size_t   index_size = ((size_t)backward_size + 1u) * 4u;

	/* ---- Read Index block ---- */
	int64_t index_offset =
		-(int64_t)XZ_STREAM_FOOTER_SIZE - (int64_t)index_size;
	if (lseek(fd, index_offset, SEEK_END) < 0)
		return DECOMP_SIZE_ERROR;

	uint8_t* index_buf = (uint8_t*)
		_alloca(index_size);
	if (read_exact(fd, index_buf, index_size))
		return DECOMP_SIZE_ERROR;

	/* ---- Parse Index ---- */
	size_t pos = 0;

	/* Indicator byte must be 0x00 */
	if (index_buf[pos++] != 0x00u)
		return DECOMP_SIZE_ERROR;

	/* Number of Records */
	uint64_t num_records = xz_read_vli(index_buf, index_size, &pos);
	if (num_records == UINT64_MAX || num_records == 0)
		return DECOMP_SIZE_ERROR;

	/* Sum uncompressed sizes across all records */
	uint64_t total = 0;
	for (uint64_t r = 0; r < num_records; r++) {
		/* Unpadded Size (compressed) — skip it */
		uint64_t unpadded = xz_read_vli(index_buf, index_size, &pos);
		if (unpadded == UINT64_MAX || unpadded == 0)
			return DECOMP_SIZE_ERROR;

		/* Uncompressed Size — accumulate */
		uint64_t uncomp = xz_read_vli(index_buf, index_size, &pos);
		if (uncomp == UINT64_MAX)
			return DECOMP_SIZE_ERROR;

		total += uncomp;
	}

	return (int64_t)total;
}

/* -------------------------------------------------------------------------
 * 7-ZIP (.7z)
 *
 * Signature Header (32 bytes at offset 0):
 *   Offset  Size  Field
 *      0      6   Signature  (0x37 0x7A 0xBC 0xAF 0x27 0x1C)
 *      6      1   Major version
 *      7      1   Minor version
 *      8      4   CRC32 of bytes 12..27
 *     12      8   NextHeader Offset  (uint64 LE, relative to offset 32)
 *     20      8   NextHeader Size    (uint64 LE)
 *     28      4   NextHeader CRC32
 *
 * The End Header lives at file offset  32 + NextHeaderOffset.
 * Its property-block stream (for a plain, non-encoded-header archive) is:
 *
 *   kHeader (0x01)
 *     kMainStreamsInfo (0x04)
 *       kPackInfo (0x06)
 *         7z-num: PackPos
 *         7z-num: NumPackStreams
 *         kSize (0x09)
 *           NumPackStreams × 7z-num packed sizes
 *         kEnd (0x00)
 *       kUnPackInfo (0x07)
 *         kFolder (0x0b)
 *           7z-num: NumFolders        (must be 1 for single-file)
 *           byte:   External          (0 = inline folder data)
 *           [inline] 7z-num: NumCoders
 *           per coder:
 *             byte: flags  (bits[3:0]=CodecIdSize, bit4=IsComplex, bit5=HasAttrs)
 *             CodecIdSize bytes: Codec ID
 *             if IsComplex: 7z-num NumInStreams, 7z-num NumOutStreams
 *             if HasAttrs:  7z-num AttrSize, AttrSize bytes Attributes
 *           [if NumCoders>1] BindPairs, PackedStreams (skipped here)
 *         kCodersUnPackSize (0x0c)
 *           7z-num: uncompressed size  ← what we want
 *         [optional kCRC (0x0a)]
 *         kEnd (0x00)
 *       [optional kSubStreamsInfo (0x08)]
 *       kEnd (0x00)
 *     [kFilesInfo (0x05) ...]
 *     kEnd (0x00)
 *
 * 7z variable-length number encoding:
 *   The first byte's leading 1-bits count how many extra bytes follow.
 *   extra=0 → value in bits[6:0] of first byte (7 bits)
 *   extra=1 → bits[5:0] of first byte + 8 bits of second (14 bits)
 *   ...
 *   extra=8 → 0xFF marker + full uint64 in next 8 bytes
 * ---------------------------------------------------------------------- */

static const uint8_t SZ_SIG[6] = { 0x37,0x7A,0xBC,0xAF,0x27,0x1C };

#define SZ_kEnd              0x00u
#define SZ_kHeader           0x01u
#define SZ_kMainStreamsInfo  0x04u
#define SZ_kPackInfo         0x06u
#define SZ_kUnPackInfo       0x07u
#define SZ_kSize             0x09u
#define SZ_kFolder           0x0Bu
#define SZ_kCodersUnPackSize 0x0Cu
#define SZ_kEncodedHeader    0x17u

/**
 * Decode one 7z variable-length number from buf[*pos], advancing *pos.
 *
 * Algorithm from the 7-zip SDK (CPP/7zip/Archive/7z/7zIn.cpp ReadNumber):
 *   mask starts at 0x80 and shifts right each iteration.
 *   While (firstByte & mask) != 0: read one more byte into low bits of value.
 *   When the stop bit is found: add (firstByte & (mask-1)) into the
 *   appropriately shifted position.
 *
 * Returns UINT64_MAX on error (buffer overrun).
 */
static uint64_t sz_read_num(const uint8_t* buf, size_t buf_len, size_t* pos)
{
	if (*pos >= buf_len) return UINT64_MAX;

	uint8_t  first = buf[(*pos)++];
	uint8_t  mask = 0x80u;
	uint64_t value = 0;

	for (int i = 0; i < 8; i++) {
		if ((first & mask) == 0) {
			/* Stop bit found: the remaining bits of first contribute here */
			uint64_t high_part = first & (uint64_t)(mask - 1u);
			value += high_part << (i * 8);
			return value;
		}
		/* Consume one more byte into bits [i*8 .. i*8+7] of value */
		if (*pos >= buf_len) return UINT64_MAX;
		value |= (uint64_t)buf[(*pos)++] << (i * 8);
		mask = (uint8_t)(mask >> 1);
	}
	/* first == 0xFF: all 8 extra bytes consumed, value is complete */
	return value;
}

static int64_t get_uncompress_size_7zip(int fd)
{
	/* ---- Read & verify Signature Header (32 bytes) ---- */
	uint8_t sig_hdr[32];
	if (lseek(fd, 0, SEEK_SET) < 0)
		return DECOMP_SIZE_ERROR;
	if (read_exact(fd, sig_hdr, 32))
		return DECOMP_SIZE_ERROR;
	if (memcmp(sig_hdr, SZ_SIG, 6) != 0)
		return DECOMP_SIZE_ERROR;

	uint64_t nh_offset = get_le64(sig_hdr + 12);
	uint64_t nh_size = get_le64(sig_hdr + 20);

	if (nh_size == 0 || nh_size > (uint64_t)64 * 1024 * 1024)
		return DECOMP_SIZE_ERROR;   /* sanity cap: 64 MiB */

	/* ---- Read End Header ---- */
	int64_t eh_abs = (int64_t)(32u + nh_offset);
	if (lseek(fd, eh_abs, SEEK_SET) < 0)  return DECOMP_SIZE_ERROR;

	uint8_t* eh = (uint8_t*)
		_alloca((size_t)nh_size);
	if (read_exact(fd, eh, (size_t)nh_size)) return DECOMP_SIZE_ERROR;

	size_t pos = 0;
	size_t len = (size_t)nh_size;

	/*
	 * Helpers that operate on (eh, len, pos) in the enclosing scope.
	 * We avoid macros that embed do-while inside comma-expressions (not
	 * valid in C99); instead use explicit checks before each read.
	 */
#define SZ_NEED(n) \
    do { if (pos + (size_t)(n) > len) return DECOMP_SIZE_ERROR; } while (0)
#define SZ_BYTE(var) \
    do { SZ_NEED(1); (var) = eh[pos++]; } while (0)
#define SZ_NUM(var) \
    do { (var) = sz_read_num(eh, len, &pos); \
         if ((var) == UINT64_MAX) return DECOMP_SIZE_ERROR; } while (0)
#define SZ_SKIP(n) \
    do { SZ_NEED(n); pos += (size_t)(n); } while (0)
#define SZ_EXPECT(tag) \
    do { uint8_t _b; SZ_BYTE(_b); \
         if (_b != (tag)) return DECOMP_SIZE_ERROR; } while (0)

	uint8_t  first_tag;
	uint64_t num_pack, num_folders, num_coders, unpack_size;

	/* Expect kHeader */
	SZ_EXPECT(SZ_kHeader);

	/* kEncodedHeader (0x17) means the real header is itself compressed;
	 * that requires decompressing a sub-stream, which we do not support. */
	SZ_NEED(1);
	if (eh[pos] == SZ_kEncodedHeader)
		return DECOMP_SIZE_ERROR;

	SZ_EXPECT(SZ_kMainStreamsInfo);
	SZ_EXPECT(SZ_kPackInfo);

	/* PackPos (discard) then NumPackStreams */
	{ uint64_t dummy; SZ_NUM(dummy); (void)dummy; }
	SZ_NUM(num_pack);

	/* kSize: skip NumPackStreams packed-size VLIs */
	SZ_EXPECT(SZ_kSize);
	for (uint64_t i = 0; i < num_pack; i++) {
		uint64_t dummy; SZ_NUM(dummy); (void)dummy;
	}
	SZ_EXPECT(SZ_kEnd);  /* closes kPackInfo */

	SZ_EXPECT(SZ_kUnPackInfo);
	SZ_EXPECT(SZ_kFolder);

	SZ_NUM(num_folders);
	if (num_folders != 1)
		return DECOMP_SIZE_ERROR;  /* only single-folder archives supported */

	{
		uint8_t external; SZ_BYTE(external);
		if (external != 0)
			return DECOMP_SIZE_ERROR;
	}  /* external not supported */

/* Parse the inline folder record to skip past coder descriptors */
	SZ_NUM(num_coders);
	if (num_coders == 0) return DECOMP_SIZE_ERROR;

	for (uint64_t c = 0; c < num_coders; c++) {
		uint8_t flags;
		SZ_BYTE(flags);
		uint8_t id_size = flags & 0x0Fu;
		int     is_complex = (flags >> 4) & 1;
		int     has_attrs = (flags >> 5) & 1;

		SZ_SKIP(id_size);   /* Codec ID bytes */

		if (is_complex) {
			uint64_t dummy;
			SZ_NUM(dummy); (void)dummy;  /* NumInStreams  */
			SZ_NUM(dummy); (void)dummy;  /* NumOutStreams */
		}
		if (has_attrs) {
			uint64_t attr_size; SZ_NUM(attr_size);
			SZ_SKIP(attr_size);
		}
	}

	/* Multi-coder folders have BindPairs and possibly PackedStreams indices */
	if (num_coders > 1) {
		for (uint64_t i = 0; i < num_coders - 1; i++) {
			uint64_t dummy;
			SZ_NUM(dummy); (void)dummy;  /* InIndex  */
			SZ_NUM(dummy); (void)dummy;  /* OutIndex */
		}
		if (num_pack > num_coders - 1) {
			uint64_t n = num_pack - (num_coders - 1);
			for (uint64_t i = 0; i < n; i++) {
				uint64_t dummy; SZ_NUM(dummy); (void)dummy;
			}
		}
	}

	/* kCodersUnPackSize: one VLI per output stream (single folder → one value) */
	SZ_NEED(1);
	first_tag = eh[pos++];
	if (first_tag != SZ_kCodersUnPackSize) return DECOMP_SIZE_ERROR;

	SZ_NUM(unpack_size);
	return (int64_t)unpack_size;

#undef SZ_NEED
#undef SZ_BYTE
#undef SZ_NUM
#undef SZ_SKIP
#undef SZ_EXPECT
}

/* -------------------------------------------------------------------------
 * Ventoy Sparse Image (.vsti)
 * ---------------------------------------------------------------------- */

static int64_t get_uncompress_size_vtsi(int fd)
{
	if (lseek(fd, -512 + 8 + 4, SEEK_END) < 0)
		return DECOMP_SIZE_ERROR;

	uint8_t isize[8];
	if (read_exact(fd, isize, 8))
		return DECOMP_SIZE_ERROR;

	return (int64_t)get_le64(isize);
}

/* -------------------------------------------------------------------------
 * Zstandard (.zst)
 *
 * Frame layout:
 *   Offset  Size  Field
 *      0      4   Magic (0xFD2FB528, LE)
 *      4      1   Frame Header Descriptor (FHD)
 *      5      0/1 Window_Descriptor (absent when Single_Segment_Flag set)
 *      ?      0/1/2/4/8  Content_Size
 *
 * FHD bits:
 *   [7:6]  Frame_Content_Size_Flag (FCS_Flag)
 *   [5]    Single_Segment_Flag     (SS_Flag)
 *   [4]    reserved (must be 0)
 *   [3]    Content_Checksum_Flag
 *   [2]    reserved (must be 0)
 *   [1:0]  Dictionary_ID_Flag
 *
 * Content_Size size from FCS_Flag:
 *   0 → 0 bytes if SS_Flag==0 (unknown), or 1 byte if SS_Flag==1
 *   1 → 2 bytes  (value + 256, to avoid overlap with 1-byte encoding)
 *   2 → 4 bytes
 *   3 → 8 bytes
 * ---------------------------------------------------------------------- */

#define ZSTD_MAGIC          UINT32_C(0xFD2FB528)
#define ZSTD_MAGIC_SIZE     4

static int64_t get_uncompress_size_zstd(int fd)
{
	uint8_t buf[4 + 1 + 1]; /* magic + FHD + optional Window_Descriptor */

	if (lseek(fd, 0, SEEK_SET) < 0)
		return DECOMP_SIZE_ERROR;
	if (read_exact(fd, buf, 6))
		return DECOMP_SIZE_ERROR;

	if (get_le32(buf) != ZSTD_MAGIC)
		return DECOMP_SIZE_ERROR;

	uint8_t fhd = buf[4];
	int     fcs_flag = (fhd >> 6) & 0x03;
	int     ss_flag = (fhd >> 5) & 0x01;

	/* Window_Descriptor is present only when Single_Segment_Flag == 0.
	 * buf[5] already consumed it; if SS_Flag==1 that byte is Content_Size[0].
	 * We'll re-seek to the correct offset to avoid confusion. */

	 /* Determine Content_Size field size. */
	int cs_bytes;
	if (fcs_flag == 0) {
		if (ss_flag == 0)
			return DECOMP_SIZE_UNKNOWN;   /* field absent */
		cs_bytes = 1;
	} else if (fcs_flag == 1) {
		cs_bytes = 2;
	} else if (fcs_flag == 2) {
		cs_bytes = 4;
	} else {
		cs_bytes = 8;
	}

	/*
	 * Content_Size starts at:
	 *   offset 5  if Single_Segment_Flag == 1 (no Window_Descriptor)
	 *   offset 6  if Single_Segment_Flag == 0 (Window_Descriptor present)
	 */
	int64_t cs_offset = (ss_flag ? 5 : 6);

	if (lseek(fd, cs_offset, SEEK_SET) < 0)
		return DECOMP_SIZE_ERROR;

	uint8_t cs_buf[8] = { 0 };
	if (read_exact(fd, cs_buf, (size_t)cs_bytes))
		return DECOMP_SIZE_ERROR;

	uint64_t size;
	switch (cs_bytes) {
	case 1:
		size = cs_buf[0];
		break;
	case 2:
		/*
		 * 2-byte encoding: actual value = field_value + 256
		 * (reserves 0-255 for the 1-byte SS_Flag path)
		 */
		size = (uint64_t)get_le16(cs_buf) + 256U;
		break;
	case 4:
		size = get_le32(cs_buf);
		break;
	default: /* 8 */
		size = get_le64(cs_buf);
		break;
	}

	return (int64_t)size;
}

#if defined(BLED_EXPECT_DISK_IMAGE)
extern progress_t bled_progress;
extern unpacker_t unpacker[BLED_COMPRESSION_MAX];
int64_t get_uncompressed_size_from_disk_image(int fd, int type)
{
	progress_t old_bled_progress = bled_progress;
	int64_t size = DECOMP_SIZE_UNKNOWN;
	uint8_t buf[8192];
	transformer_state_t xstate;

	bled_progress = NULL;	/* Can't have progress on this operation */
	init_transformer_state(&xstate);
	xstate.src_fd = fd;
	xstate.dst_fd = -1;
	xstate.mem_output_buf = buf;
	xstate.mem_output_size = 0;
	xstate.mem_output_size_max = sizeof(buf);

	if (setjmp(bb_error_jmp))
		goto out;

	lseek(fd, 0, SEEK_SET);
	size = unpacker[type](&xstate);
	if (size != sizeof(buf) || buf[0x1fe] != 0x55 || buf[0x1ff] != 0xaa) {
		size = DECOMP_SIZE_UNKNOWN;
		goto out;
	}
	if (buf[0x1c2] == 0xee) {
		/* Protective EFI MBR => look for the primary GPT, which'll also give us the sector size */
		if (memcmp("EFI PART", &buf[0x200], 8) == 0) {
			/* The address of the backup GPT is assumed to be the last LBA for the disk */
			size = get_le64(&buf[0x220]) * 512;
			goto out;
		}
		if (memcmp("EFI PART", &buf[0x1000], 8) == 0) {
			size = get_le64(&buf[0x1020]) * 8192;
			goto out;
		}
	}
	if (buf[0x1be] == 0x80) {
		/* Regular bootable MBR => compute the max LBA (using primary partitions only) */
		uint32_t max_lba = 1;
		for (int i = 0; i < 4; i++)
			max_lba = MAX(max_lba, get_le32(&buf[0x1be + 0x10 * i + 8]) + get_le32(&buf[0x1be + 0x10 * i + 0xc]));
		size = max_lba * 512;	/* assume 512-byte sectors for anything MBR based */
		if (size < 8192)
			size = DECOMP_SIZE_UNKNOWN;
	}

out:
	bled_progress = old_bled_progress;
	return size;
}
#endif

static get_uncompressed_size_t _get_uncompressed_size[BLED_COMPRESSION_MAX] = {
	get_uncompress_size_none,
	get_uncompress_size_zip,
	get_uncompress_size_none,	// .Z has no decompressed size info
	get_uncompress_size_gz,
	get_uncompress_size_lzma,
	get_uncompress_size_none,	// .bz2 has no decompressed size info
	get_uncompress_size_xz,
	get_uncompress_size_7zip,
	get_uncompress_size_vtsi,
	get_uncompress_size_zstd,
};

/* Get the decompressed size of file 'fd', compressed using 'type' */
int64_t get_uncompressed_size(int fd, int type)
{
	int64_t size = _get_uncompressed_size[type](fd);
#if defined(BLED_EXPECT_DISK_IMAGE)
	if (size < 0)
		size = get_uncompressed_size_from_disk_image(fd, type);
#endif

	/* Make sure to reset our file pointer */
	lseek(fd, 0, SEEK_SET);
	return size;
}
